### ISSUE TITLE
Create Statix Yeoman generator

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/statix#1]
I think that Statix could be made into a Yeoman generator so that developers using other frameworks, besides [Kickoff](https://github.com/tmwagency/kickoff), should be able to benefit. Could we include options for Bootstrap, Foundation and any others as well as Kickoff?

**Comment by ashleynolan** [comment]
I think this is a brilliant idea – I do think that to keep it up-to-date, we would probably need to get help from members of each community to update specific frameworks.

Could be worth trying to do this for a large framework like Bootstrap/Zend first and set it up so that it would be relatively easy for people to add their own frameworks too so that it can grow.

Will take a look into.

**Comment by ashleynolan** [comment]
So having thought about this a fair bit (and hopefully soon to have a bit of time to maybe look into this), it may be worth trying to do this with a popular but more modest framework, such as Inuit, first as a test case.

I think that a Statix generator would probably lend itself best when combined with just the CSS aspects of  frameworks, so by taking a CSS only framework first as a trial and then maybe moving onto using just the CSS from Bootstrap or Zend would be a couple of good use cases.

I might need a little bit of help with setting up the base Yeoman generator from @mrmartineau, but still thinking that this is a good idea.  Let’s get the ball rolling on this one…!

**Comment by rentorm** [comment]
Is this still actual?

**Comment by ashleynolan** [comment]
It’s still an idea – not sure I’ll ever get time to work on it though ;)

Going to close this for now, as it’s more of a future idea, that could be reopened at some point.
